# Generated by Django 2.1.7 on 2019-02-25 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 12, 36, 30, 446429, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
