# Generated by Django 2.1.7 on 2019-02-25 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190225_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 25, 12, 37, 32, 965443, tzinfo=utc)),
        ),
    ]
