# Generated by Django 2.1.7 on 2019-02-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190225_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='TBD', max_length=20),
            preserve_default=False,
        ),
    ]
