# Generated by Django 2.1.7 on 2019-02-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190226_0703'),
        ('events', '0007_auto_20190226_0643'),
    ]

    operations = [
    ]
