# Generated by Django 2.1.7 on 2019-02-26 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_merge_20190226_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organized_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL),
        ),
    ]
